// Copyright 2020-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import TReadOnlyProperty from '../../axon/js/TReadOnlyProperty.js';
import areaModelCommon from './areaModelCommon.js';

type StringsType = {
  'screen': {
    'explore': string;
    'exploreStringProperty': TReadOnlyProperty<string>;
    'generic': string;
    'genericStringProperty': TReadOnlyProperty<string>;
    'variables': string;
    'variablesStringProperty': TReadOnlyProperty<string>;
    'multiply': string;
    'multiplyStringProperty': TReadOnlyProperty<string>;
    'partition': string;
    'partitionStringProperty': TReadOnlyProperty<string>;
    'decimals': string;
    'decimalsStringProperty': TReadOnlyProperty<string>;
    'game': string;
    'gameStringProperty': TReadOnlyProperty<string>;
  };
  'dimensions': string;
  'dimensionsStringProperty': TReadOnlyProperty<string>;
  'factors': string;
  'factorsStringProperty': TReadOnlyProperty<string>;
  'totalAreaOfModel': string;
  'totalAreaOfModelStringProperty': TReadOnlyProperty<string>;
  'product': string;
  'productStringProperty': TReadOnlyProperty<string>;
  'partition': string;
  'partitionStringProperty': TReadOnlyProperty<string>;
  'areaModelCalculation': string;
  'areaModelCalculationStringProperty': TReadOnlyProperty<string>;
  'calculation': string;
  'calculationStringProperty': TReadOnlyProperty<string>;
  'partialProducts': string;
  'partialProductsStringProperty': TReadOnlyProperty<string>;
  'enter': string;
  'enterStringProperty': TReadOnlyProperty<string>;
  'area': string;
  'areaStringProperty': TReadOnlyProperty<string>;
  'scorePrefix': string;
  'scorePrefixStringProperty': TReadOnlyProperty<string>;
  'levelPrompt': {
    'totalArea': string;
    'totalAreaStringProperty': TReadOnlyProperty<string>;
    'oneProduct': {
      'text': string;
      'textStringProperty': TReadOnlyProperty<string>;
      'totalArea': string;
      'totalAreaStringProperty': TReadOnlyProperty<string>;
      'oneLength': string;
      'oneLengthStringProperty': TReadOnlyProperty<string>;
    };
    'twoProducts': string;
    'twoProductsStringProperty': TReadOnlyProperty<string>;
    'twoLengths': string;
    'twoLengthsStringProperty': TReadOnlyProperty<string>;
    'threeLengths': string;
    'threeLengthsStringProperty': TReadOnlyProperty<string>;
  };
  'a11y': {
    'areaEqualsPattern': string;
    'areaEqualsPatternStringProperty': TReadOnlyProperty<string>;
    'areaGrid': string;
    'areaGridStringProperty': TReadOnlyProperty<string>;
    'areaGridRectanglePattern': string;
    'areaGridRectanglePatternStringProperty': TReadOnlyProperty<string>;
    'areaGridSize': string;
    'areaGridSizeStringProperty': TReadOnlyProperty<string>;
    'base10AreaTiles': string;
    'base10AreaTilesStringProperty': TReadOnlyProperty<string>;
    'betweenCalculationLines': string;
    'betweenCalculationLinesStringProperty': TReadOnlyProperty<string>;
    'calculationBoxTitle': string;
    'calculationBoxTitleStringProperty': TReadOnlyProperty<string>;
    'calculationBoxDescription': string;
    'calculationBoxDescriptionStringProperty': TReadOnlyProperty<string>;
    'countingNumbersDescription': string;
    'countingNumbersDescriptionStringProperty': TReadOnlyProperty<string>;
    'countingNumbersLabel': string;
    'countingNumbersLabelStringProperty': TReadOnlyProperty<string>;
    'countingNumbersPattern': string;
    'countingNumbersPatternStringProperty': TReadOnlyProperty<string>;
    'dragHandle': string;
    'dragHandleStringProperty': TReadOnlyProperty<string>;
    'dragHandleDescriptionPattern': string;
    'dragHandleDescriptionPatternStringProperty': TReadOnlyProperty<string>;
    'erase': string;
    'eraseStringProperty': TReadOnlyProperty<string>;
    'eraseDescription': string;
    'eraseDescriptionStringProperty': TReadOnlyProperty<string>;
    'factorsBox': string;
    'factorsBoxStringProperty': TReadOnlyProperty<string>;
    'factorsBoxDescription': string;
    'factorsBoxDescriptionStringProperty': TReadOnlyProperty<string>;
    'factorsTimesPattern': string;
    'factorsTimesPatternStringProperty': TReadOnlyProperty<string>;
    'gridLinesLabel': string;
    'gridLinesLabelStringProperty': TReadOnlyProperty<string>;
    'hidePartialProducts': string;
    'hidePartialProductsStringProperty': TReadOnlyProperty<string>;
    'horizontalDimensionCapitalized': string;
    'horizontalDimensionCapitalizedStringProperty': TReadOnlyProperty<string>;
    'horizontalPartition': string;
    'horizontalPartitionStringProperty': TReadOnlyProperty<string>;
    'horizontalPartitionHandle': string;
    'horizontalPartitionHandleStringProperty': TReadOnlyProperty<string>;
    'horizontalPartitionHandleDescription': string;
    'horizontalPartitionHandleDescriptionStringProperty': TReadOnlyProperty<string>;
    'horizontalPicker': string;
    'horizontalPickerStringProperty': TReadOnlyProperty<string>;
    'horizontalPickerDescription': string;
    'horizontalPickerDescriptionStringProperty': TReadOnlyProperty<string>;
    'multiplyDescription': string;
    'multiplyDescriptionStringProperty': TReadOnlyProperty<string>;
    'onePartialProductFactorPattern': string;
    'onePartialProductFactorPatternStringProperty': TReadOnlyProperty<string>;
    'onePartialProductPattern': string;
    'onePartialProductPatternStringProperty': TReadOnlyProperty<string>;
    'partitionDescription': string;
    'partitionDescriptionStringProperty': TReadOnlyProperty<string>;
    'partitionSelectionDescription': string;
    'partitionSelectionDescriptionStringProperty': TReadOnlyProperty<string>;
    'placeholder': string;
    'placeholderStringProperty': TReadOnlyProperty<string>;
    'productBox': string;
    'productBoxStringProperty': TReadOnlyProperty<string>;
    'productBoxDescription': string;
    'productBoxDescriptionStringProperty': TReadOnlyProperty<string>;
    'productTimesPattern': string;
    'productTimesPatternStringProperty': TReadOnlyProperty<string>;
    'quantityPattern': string;
    'quantityPatternStringProperty': TReadOnlyProperty<string>;
    'questionMark': string;
    'questionMarkStringProperty': TReadOnlyProperty<string>;
    'sceneSelectionPattern': string;
    'sceneSelectionPatternStringProperty': TReadOnlyProperty<string>;
    'showPartialProductFactors': string;
    'showPartialProductFactorsStringProperty': TReadOnlyProperty<string>;
    'showPartialProducts': string;
    'showPartialProductsStringProperty': TReadOnlyProperty<string>;
    'sumMinus': string;
    'sumMinusStringProperty': TReadOnlyProperty<string>;
    'sumPlus': string;
    'sumPlusStringProperty': TReadOnlyProperty<string>;
    'threePartitionsSplitPattern': string;
    'threePartitionsSplitPatternStringProperty': TReadOnlyProperty<string>;
    'twoPartialProductFactorsPattern': string;
    'twoPartialProductFactorsPatternStringProperty': TReadOnlyProperty<string>;
    'twoPartialProductsPattern': string;
    'twoPartialProductsPatternStringProperty': TReadOnlyProperty<string>;
    'twoPartitionsSplitPattern': string;
    'twoPartitionsSplitPatternStringProperty': TReadOnlyProperty<string>;
    'verticalDimensionCapitalized': string;
    'verticalDimensionCapitalizedStringProperty': TReadOnlyProperty<string>;
    'verticalPartition': string;
    'verticalPartitionStringProperty': TReadOnlyProperty<string>;
    'verticalPartitionHandle': string;
    'verticalPartitionHandleStringProperty': TReadOnlyProperty<string>;
    'verticalPartitionHandleDescription': string;
    'verticalPartitionHandleDescriptionStringProperty': TReadOnlyProperty<string>;
    'verticalPicker': string;
    'verticalPickerStringProperty': TReadOnlyProperty<string>;
    'verticalPickerDescription': string;
    'verticalPickerDescriptionStringProperty': TReadOnlyProperty<string>;
  }
};

const AreaModelCommonStrings = getStringModule( 'AREA_MODEL_COMMON' ) as StringsType;

areaModelCommon.register( 'AreaModelCommonStrings', AreaModelCommonStrings );

export default AreaModelCommonStrings;
