// Copyright 2020-2023, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import type LocalizedStringProperty from '../../chipper/js/LocalizedStringProperty.js';
import areaModelCommon from './areaModelCommon.js';

type StringsType = {
  'screen': {
    'explore': string;
    'exploreStringProperty': LocalizedStringProperty;
    'generic': string;
    'genericStringProperty': LocalizedStringProperty;
    'variables': string;
    'variablesStringProperty': LocalizedStringProperty;
    'multiply': string;
    'multiplyStringProperty': LocalizedStringProperty;
    'partition': string;
    'partitionStringProperty': LocalizedStringProperty;
    'decimals': string;
    'decimalsStringProperty': LocalizedStringProperty;
    'game': string;
    'gameStringProperty': LocalizedStringProperty;
  };
  'dimensions': string;
  'dimensionsStringProperty': LocalizedStringProperty;
  'factors': string;
  'factorsStringProperty': LocalizedStringProperty;
  'totalAreaOfModel': string;
  'totalAreaOfModelStringProperty': LocalizedStringProperty;
  'product': string;
  'productStringProperty': LocalizedStringProperty;
  'partition': string;
  'partitionStringProperty': LocalizedStringProperty;
  'areaModelCalculation': string;
  'areaModelCalculationStringProperty': LocalizedStringProperty;
  'calculation': string;
  'calculationStringProperty': LocalizedStringProperty;
  'partialProducts': string;
  'partialProductsStringProperty': LocalizedStringProperty;
  'enter': string;
  'enterStringProperty': LocalizedStringProperty;
  'area': string;
  'areaStringProperty': LocalizedStringProperty;
  'scorePrefix': string;
  'scorePrefixStringProperty': LocalizedStringProperty;
  'levelPrompt': {
    'totalArea': string;
    'totalAreaStringProperty': LocalizedStringProperty;
    'oneProduct': {
      'text': string;
      'textStringProperty': LocalizedStringProperty;
      'totalArea': string;
      'totalAreaStringProperty': LocalizedStringProperty;
      'oneLength': string;
      'oneLengthStringProperty': LocalizedStringProperty;
    };
    'twoProducts': string;
    'twoProductsStringProperty': LocalizedStringProperty;
    'twoLengths': string;
    'twoLengthsStringProperty': LocalizedStringProperty;
    'threeLengths': string;
    'threeLengthsStringProperty': LocalizedStringProperty;
  };
  'a11y': {
    'areaEqualsPattern': string;
    'areaEqualsPatternStringProperty': LocalizedStringProperty;
    'areaGrid': string;
    'areaGridStringProperty': LocalizedStringProperty;
    'areaGridRectanglePattern': string;
    'areaGridRectanglePatternStringProperty': LocalizedStringProperty;
    'areaGridSize': string;
    'areaGridSizeStringProperty': LocalizedStringProperty;
    'base10AreaTiles': string;
    'base10AreaTilesStringProperty': LocalizedStringProperty;
    'betweenCalculationLines': string;
    'betweenCalculationLinesStringProperty': LocalizedStringProperty;
    'calculationBoxTitle': string;
    'calculationBoxTitleStringProperty': LocalizedStringProperty;
    'calculationBoxDescription': string;
    'calculationBoxDescriptionStringProperty': LocalizedStringProperty;
    'countingNumbersDescription': string;
    'countingNumbersDescriptionStringProperty': LocalizedStringProperty;
    'countingNumbersLabel': string;
    'countingNumbersLabelStringProperty': LocalizedStringProperty;
    'countingNumbersPattern': string;
    'countingNumbersPatternStringProperty': LocalizedStringProperty;
    'dragHandle': string;
    'dragHandleStringProperty': LocalizedStringProperty;
    'dragHandleDescriptionPattern': string;
    'dragHandleDescriptionPatternStringProperty': LocalizedStringProperty;
    'erase': string;
    'eraseStringProperty': LocalizedStringProperty;
    'eraseDescription': string;
    'eraseDescriptionStringProperty': LocalizedStringProperty;
    'factorsBox': string;
    'factorsBoxStringProperty': LocalizedStringProperty;
    'factorsBoxDescription': string;
    'factorsBoxDescriptionStringProperty': LocalizedStringProperty;
    'factorsTimesPattern': string;
    'factorsTimesPatternStringProperty': LocalizedStringProperty;
    'gridLinesLabel': string;
    'gridLinesLabelStringProperty': LocalizedStringProperty;
    'hidePartialProducts': string;
    'hidePartialProductsStringProperty': LocalizedStringProperty;
    'horizontalDimensionCapitalized': string;
    'horizontalDimensionCapitalizedStringProperty': LocalizedStringProperty;
    'horizontalPartition': string;
    'horizontalPartitionStringProperty': LocalizedStringProperty;
    'horizontalPartitionHandle': string;
    'horizontalPartitionHandleStringProperty': LocalizedStringProperty;
    'horizontalPartitionHandleDescription': string;
    'horizontalPartitionHandleDescriptionStringProperty': LocalizedStringProperty;
    'horizontalPicker': string;
    'horizontalPickerStringProperty': LocalizedStringProperty;
    'horizontalPickerDescription': string;
    'horizontalPickerDescriptionStringProperty': LocalizedStringProperty;
    'multiplyDescription': string;
    'multiplyDescriptionStringProperty': LocalizedStringProperty;
    'onePartialProductFactorPattern': string;
    'onePartialProductFactorPatternStringProperty': LocalizedStringProperty;
    'onePartialProductPattern': string;
    'onePartialProductPatternStringProperty': LocalizedStringProperty;
    'partitionDescription': string;
    'partitionDescriptionStringProperty': LocalizedStringProperty;
    'partitionSelectionDescription': string;
    'partitionSelectionDescriptionStringProperty': LocalizedStringProperty;
    'placeholder': string;
    'placeholderStringProperty': LocalizedStringProperty;
    'productBox': string;
    'productBoxStringProperty': LocalizedStringProperty;
    'productBoxDescription': string;
    'productBoxDescriptionStringProperty': LocalizedStringProperty;
    'productTimesPattern': string;
    'productTimesPatternStringProperty': LocalizedStringProperty;
    'quantityPattern': string;
    'quantityPatternStringProperty': LocalizedStringProperty;
    'questionMark': string;
    'questionMarkStringProperty': LocalizedStringProperty;
    'sceneSelectionPattern': string;
    'sceneSelectionPatternStringProperty': LocalizedStringProperty;
    'showPartialProductFactors': string;
    'showPartialProductFactorsStringProperty': LocalizedStringProperty;
    'showPartialProducts': string;
    'showPartialProductsStringProperty': LocalizedStringProperty;
    'sumMinus': string;
    'sumMinusStringProperty': LocalizedStringProperty;
    'sumPlus': string;
    'sumPlusStringProperty': LocalizedStringProperty;
    'threePartitionsSplitPattern': string;
    'threePartitionsSplitPatternStringProperty': LocalizedStringProperty;
    'twoPartialProductFactorsPattern': string;
    'twoPartialProductFactorsPatternStringProperty': LocalizedStringProperty;
    'twoPartialProductsPattern': string;
    'twoPartialProductsPatternStringProperty': LocalizedStringProperty;
    'twoPartitionsSplitPattern': string;
    'twoPartitionsSplitPatternStringProperty': LocalizedStringProperty;
    'verticalDimensionCapitalized': string;
    'verticalDimensionCapitalizedStringProperty': LocalizedStringProperty;
    'verticalPartition': string;
    'verticalPartitionStringProperty': LocalizedStringProperty;
    'verticalPartitionHandle': string;
    'verticalPartitionHandleStringProperty': LocalizedStringProperty;
    'verticalPartitionHandleDescription': string;
    'verticalPartitionHandleDescriptionStringProperty': LocalizedStringProperty;
    'verticalPicker': string;
    'verticalPickerStringProperty': LocalizedStringProperty;
    'verticalPickerDescription': string;
    'verticalPickerDescriptionStringProperty': LocalizedStringProperty;
  };
  'characterSet': {
    'unitedStatesOfAmerica': string;
    'unitedStatesOfAmericaStringProperty': LocalizedStringProperty;
  }
};

const AreaModelCommonStrings = getStringModule( 'AREA_MODEL_COMMON' ) as StringsType;

areaModelCommon.register( 'AreaModelCommonStrings', AreaModelCommonStrings );

export default AreaModelCommonStrings;
